title: Claudine Chionh
description: Claudine's GLAMR/tech blog
languageCode: en-au
timeZone: Australia/Melbourne
theme: github.com/panr/hugo-theme-terminal
enableGitInfo: true
copyright: © Claudine Chionh (CC-BY-SA-4.0)
paginate: 5
cleanDestinationDir: true
