title: claudinec.net
languageCode: en-au
timeZone: Australia/Melbourne
enableGitInfo: true
copyright: © Claudine Chionh (CC-BY-SA-4.0).
paginate: 5
cleanDestinationDir: true
buildExpired: false
capitalizeListTitles: false
enableEmoji: true
module:
    imports:
        - path: github.com/adityatelange/hugo-PaperMod
theme: github.com/adityatelange/hugo-PaperMod
