main:
- identifier: about
  name: About
  url: /about
  weight: 5
- identifier: cv
  name: CV
  url: /cv
  weight: 10
- identifier: mastodonAusSocial
  name: Aus.Social
  url: https://aus.social/@claudinec
  weight: 21
- identifier: mastodonFosstodon
  name: Fosstodon
  url: https://fosstodon.org/@claudinec
  weight: 22
