author: Claudine Chionh
dateform: 2 Jan 2006
dateformShort: 2 Jan
dateformNum: 2006-01-02
dateformNumTime: 2006-01-02 15:04 -0700
contentTypeName: posts
fullWidthTheme: false
centerTheme: true
themeColor: blue
logo: 
  logoText: Claudine Chionh
  logoHomeLink: /
