author: "Claudine Chionh"
dateFormat: "2 Jan 2006"
contentTypeName: "posts"
defaultTheme: "auto"
label:
    icon: "/memoji-128x128.png"
assets:
    favicon: "memoji-128x128.png"
    apple_touch_icon: "memoji-128x128.png"

homeInfoParams:
    title: "Claudine Chionh"
    content: "Newbie archivist and recovering webdev"
    buttons:
        - name: "Posts"
          url: "/posts"
socialIcons:
    - name: "sourcehut"
      url: "https://sr.ht/~claudinec/"
    - name: "github"
      url: "https://github.com/claudinec"
    - name: "mastodon"
      url: "https://aus.social/@claudinec"
    - name: "pgp"
      url: "https://keyoxide.org/8B825A69DFB6DED67697C7EB19611CA3BA9E8059"
editPost:
    url: "mailto:~claudinec/public-inbox@lists.sr.ht?subject="
    text: "Email comments (public inbox)"
    appendFilePath: true

