author: "Claudine Chionh"
dateFormat: "2 Jan 2006"
contentTypeName: "posts"
defaultTheme: "auto"
label:
    icon: "/memoji-128x128.png"
assets:
    favicon: "memoji-128x128.png"
    favicon16x16: "memoji-16x16.png"
    favicon32x32: "memoji-32x32.png"
    apple_touch_icon: "memoji-128x128.png"
    safari_pinned_tab: "memoji-128x128.svg"

homeInfoParams:
    title: "Claudine Chionh"
    content: "Newbie archivist and recovering webdev"
    buttons:
        - name: "Posts"
          url: "/posts"
socialIcons:
    - name: "wikipedia"
      url: "https://en.wikipedia.org/wiki/User:ClaudineChionh"
    - name: "sourcehut"
      url: "https://sr.ht/~claudinec/"
    - name: "github"
      url: "https://github.com/claudinec"
    - name: "mastodon"
      url: "https://aus.social/@claudinec"
    - name: "bluesky"
      url: "https://bsky.app/profile/claudinec.net"
    - name: "email"
      url: "mailto:hello+www@claudinec.net"
editPost:
    url: "mailto:hello+www@claudinec.net?subject=Comment%20on%20"
    text: "Email me about this page"
    appendFilePath: true
ShowBreadCrumbs: true

