main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: 10
    - identifier: about
      name: About
      url: /about
      weight: 20
    - identifier: reading
      name: Reading
      url: /reading
      weight: 21
    - identifier: uses
      name: Uses
      url: /uses
      weight: 30
