baseURL = "http://www.claudinec.net/"
languageCode = "en-au"
title = "Claudine Chionh"
theme = "hugo-xmin"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/claudine-chionh.pdf"
    weight = 2

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/claudinec"
    weight = 12

  [[menu.main]]
    identifier = "so-story"
    name = "Stack Overflow"
    url = "https://stackoverflow.com/story/claudinec"
    weight = 13

  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/claudinec"
    weight = 14

  [[menu.main]]
    identifier = "keybase"
    name = "Keybase"
    url = "https://keybase.io/claudinec"
    weight = 15

  [[menu.main]]
    identifier = "email"
    name = "Email"
    url = "mailto:public@claudinec.net"
    weight = 20

[params]
  author = "Claudine Chionh"
  footer = "Created with [Hugo](https://gohugo.io/) | [XMin theme](https://xmin.yihui.name/)"
