baseURL = "https://www.claudinec.net/"
languageCode = "en-au"
title = "Claudine Chionh"
theme = "hugo-xmin"
paginate = 5

[author]
  name = "Claudine Chionh"

[params]
  author = "Claudine Chionh"
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle    = "Words, stories, tech"
  contentTypeName = "posts"
  fullWidthTheme  = false
  centerTheme     = true
  themeColor      = "blue"

  [params.logo]
    logoText = "Home"
    logoHomeLink = "/"
