baseURL: https://www.claudinec.net/
title: Claudine Chionh
languageCode: en-au
timeZone: Australia/Melbourne
theme: github.com/panr/hugo-theme-terminal
enableGitInfo: true
frontmatter:
  date:
  - :filename
  lastmod:
  - lastmod
  - :git
  - :default
paginate: 5
params: 
  author: Claudine Chionh
  dateform: 2 Jan 2006
  dateformShort: 2 Jan
  dateformNum: 2006-01-02
  dateformNumTime: 2006-01-02 15:04 -0700
  contentTypeName: posts
  fullWidthTheme: false
  centerTheme: true
  themeColor: blue
  logo: 
    logoText: Claudine Chionh
    logoHomeLink: /
menu: 
  main:
  - identifier: about
    name: About
    url: /about
    weight: 5
  - identifier: cv
    name: CV
    url: /cv
    weight: 10
  - identifier: github
    name: GitHub
    url: https://github.com/claudinec
    weight: 20
  - identifier: linkedin
    name: LinkedIn
    url: https://www.linkedin.com/in/claudinec/
    weight: 30
  - identifier: twitter
    name: Twitter
    url: https://twitter.com/claudinec
    weight: 40
  - identifier: pgp
    name: PGP
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/8E4D0A0773D49C4F3760E94EA75C2F000E3E5921
    weight: 50
  - identifier: email
    name: Email
    url: mailto:info@claudinec.net
    weight: 60
