baseURL = "http://www.claudinec.net/"
languageCode = "en-au"
title = "Claudine Chionh"
theme = "hugo-xmin"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

[params]
  author = "Claudine Chionh"
  footer = "Created with [Hugo](https://gohugo.io/) | [XMin theme](https://xmin.yihui.name/)"
