baseURL = "https://www.claudinec.net/"
languageCode = "en-au"
title = "Claudine Chionh"
theme = "hugo-dusk"
paginate = 5
pygmentsStyle = "native"
pygmentsCodeFences = true

[author]
  name = "Claudine Chionh"

[params]
  author = "Claudine Chionh"
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle    = "Words, stories, tech"
  contentTypeName = "posts"
  github          = "claudinec"
  twitter         = "claudinec"
  linkedin        = "claudinec"
  email           = "info@claudinec.net"
