baseURL = "https://www.claudinec.net/"
# languageCode = "en-au"
title = "Claudine Chionh"
theme = "hugo-xmin"
paginate = 5

[author]
  name = "Claudine Chionh"

[params]
  author = "Claudine Chionh"
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle    = "Words, stories, tech"
  contentTypeName = "posts"
  fullWidthTheme  = false
  centerTheme     = true
  themeColor      = "blue"

  [params.logo]
    logoText = "Claudine Chionh"
    logoHomeLink = "/"

[menu]

  [[menu.main]]
    identfier = "about"
    name      = "About"
    url       = "/about"
    weight    = 5

  [[menu.main]]
    identfier = "cv"
    name      = "CV"
    url       = "/cv"
    weight    = 10

  [[menu.main]]
    identfier = "github"
    name      = "GitHub"
    url       = "https://github.com/claudinec"
    weight    = 20

  [[menu.main]]
    identfier = "linkedin"
    name      = "LinkedIn"
    url       = "https://www.linkedin.com/in/claudinec/"
    weight    = 30

  [[menu.main]]
    identfier = "twitter"
    name      = "Twitter"
    url       = "https://twitter.com/claudinec"
    weight    = 40

  # [[menu.main]]
  #   identfier = "pgp"
  #   name      = "PGP"
  #   url       = "https://keys.openpgp.org/vks/v1/by-fingerprint/8E4D0A0773D49C4F3760E94EA75C2F000E3E5921"
  #   weight    = 50

  # [[menu.main]]
  #   identfier = "email"
  #   name      = "Email"
  #   url       = "mailto:info@claudinec.net"
  #   weight    = 60

