main:
    - identifier: hello
      name: Hello
      pageRef: /hello
      weight: 5
    - identifier: posts
      name: Posts
      pageRef: /posts
      weight: 10
    - identifier: resources
      name: Resources
      pageRef: /resources
      weight: 15
    - identifier: about
      name: About
      pageRef: /about
      weight: 20
    - identifier: reading
      name: Reading
      pageRef: /reading
      weight: 21
    - identifier: uses
      name: Uses
      pageRef: /uses
      weight: 30
