main:
    - identifier: hello
      name: Hello
      pageRef: /hello
      weight: 10
    - identifier: about
      name: About
      pageRef: /about
      weight: 11
    - identifier: reading
      name: Reading
      pageRef: /reading
      weight: 21
    - identifier: uses
      name: Uses
      pageRef: /uses
      weight: 22
    - identifier: posts
      name: Posts
      pageRef: /posts
      weight: 30
    - identifier: tags
      name: Tags
      pageRef: /tags
      weight: 40
    - identifier: feeds
      name: Feeds
      pageRef: /feeds
      weight: 50
    - identifier: search
      name: Search
      pageRef: /search
      weight: 60
 
 
